class_name ExplosiveWeapon extends WeaponType

## The mutable stats for the weapon
@export
var stats: ExplosiveWeaponStats

## The radius of explosions generated by the weapon.
@export var explosion_radius: float = 0.0

## The type of enemy the weapon targets
@export var target_priority: TargetPriority
